Update - qui abr 27 09:44:28 -03 2017

diff --git a/deploy/deploy b/deploy/deploy
--- a/deploy/deploy
+++ b/deploy/deploy
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 
-
+# source ~/.bashrc
 
 
 prompt1="Enter your option: "
@@ -33,13 +33,22 @@ function _enter_branch(){
 function _verify_remote(){
   get_remote=$(git remote -v)
   if [[ -z $get_remote ]]; then
-    printf "[Error] Remote address not reported. Set it!\n"
+    printf "[Error] Remote address not add. Set it!\n"
     exit 1
   fi
 }
 
 function _get_origin_name(){
   origin_name=$(git remote -v | awk '{ print $1 }' | sed '2d')
+}
+
+function _verify_bundle_and_jekyll(){
+  if [[ ! -f $(echo "$GEM_BIN/bundle") ]] || [[ ! -f $(echo "$BUNDLE_BIN/jekyll") ]]; then
+    echo \$BUNDLE_BIN
+   printf "[Error] To perform the deploy of the compiled project. You need to have the Bundler installed and Jekyll installed through the Bundler. \n\n"
+   exit 1
+  fi
+   bundle exec jekyll b
 }
 
 function _select_type_deploy(){
@@ -58,15 +67,23 @@ function _select_type_deploy(){
   type_branch="$list"
 
   if [[ "$type_branch" == "Compiled" ]]; then
+    _verify_bundle_and_jekyll
     _get_destination "_config.yml"
     printf "\nYou are inside the folder: ${destination_build} \n"
     printf "This folder is the compiled project folder.\n"
     _enter_foloder $destination_build
-    _select_branch
   else
     printf "\n[Ok! You have chosen to deploy your source code.] \n\n"
-    _select_branch
   fi
+}
+
+function _start_commit(){
+  git add .
+  git commit -m "Update - $(date)"
+}
+
+function _start_push(){
+   git push $1 $2
 }
 
 # Function select branch deploy
@@ -79,6 +96,10 @@ function _select_branch(){
   branch_list=( $(git branch --list | cut -d'*' -f2) )
 # branch_list=( $(git branch --list | sed 's/ /-/g') )
 # branch_list=( $(git branch --list | sed 's/*/[default]/g' | sed 's/ /-/g') )
+
+  if [[ -z $branch_list ]]; then
+    _start_commit
+  fi
 
   PS3="$prompt1"
   printf "Options:\n\n"
@@ -96,10 +117,11 @@ function _select_branch(){
 function _start_deploy(){
   _verify_remote
   _select_type_deploy
+  _select_branch
   _get_origin_name
-  git add .
-  git commit -m "Update - $(date)"
-  git push $origin_name $branch_deploy
+
+  _start_commit
+  _start_push "$origin_name" "$branch_deploy"
 }
 
 _start_deploy
